#!/bin/bash

# ./divide_and_run.sh <simulation_name> <traffic_request_file_name> <topology_file_name> <run_file_name> <num_of_processes>

if (( $# != 5 )); 
then 
  echo "./divide_and_run.sh <simulation_name> <traffic_request_file_name> <topology_file_name> <run_file_name> <num_of_processes>"
  exit 1
fi

# arguments
sim_name=$1
traffic_request=$2
topology=$3
run_file=$4
process_count=$5

# create dir
folder_name=/home/mfbari/middlebox-placement/src/"$sim_name"_"$(date +%Y%m%d_%H%M%S)"
mkdir -p $folder_name

# partitioning of time instances
time_instances=($(cat "$traffic_request" | cut -d',' -f1 | sort -n | uniq))
time_instance_count=${#time_instances[@]}
partition_size=$((time_instance_count/process_count))
partition_points=()

# for last partition
if [ $(($time_instance_count % $process_count)) -gt 0 ]
then
  ((partition_size++))
fi

# populate the partition points 
for (( i=0; i<$process_count; i++ ))
do
  partition_points[$i]=${time_instances[$(($partition_size*$i))]}
done
# for indicating the last partition insert -1
partition_points[$i]=-1

echo "$partition_size" " time instances per process"

# partition the input file and run the program
start_ts=${partition_points[0]}
for ((i=0; i<$process_count; i++ ))
do
  end_ts=${partition_points[$(($i+1))]}

  start_ln=$((`grep -n -m 1 "^$start_ts" $traffic_request | awk -F: '{print $1}'`))
  if [ $end_ts -eq -1 ]
  then
    end_ts=$((`tail -n1 $traffic_request | cut -d',' -f1`))
    end_ln=$((`wc -l < $traffic_request`))
  else
    end_ln=$((`grep -n -m 1 "^$end_ts" $traffic_request | awk -F: '{print $1}'`-1))
  fi  
  
  sub_folder_name=$folder_name/run_"$start_ts"_"$end_ts"
  `mkdir -p $sub_folder_name`

  ## copy all input files in the subfolder
  `cp middleman "$run_file" "$topology" middlebox-spec "$sub_folder_name"/`
  `sed -n "$start_ln","$end_ln"p $traffic_request > "$sub_folder_name"/$traffic_request`

  ## run the processes
  (cd "$sub_folder_name" && `cat "$run_file"` > output &)

  start_ts=$(($end_ts))
done

