#!/bin/bash

traffic_request=$1

time_instances=($(cat "$traffic_request" | cut -d',' -f1 | sort -n | uniq))
time_instance_count=${#time_instances[@]}

for (( i=0; i<$time_instance_count; i++ ))
do
 load=$((`cat $traffic_request | grep ^"${time_instances[$i]}" | cut -d',' -f4 | awk 'BEGIN {s=0;} {s+=$1;} END {print s;}'`))
 echo "${time_instances[$i]} $load"
done
